spring:
  application:
    name: shop
  mvc:
    view:
      suffix: .html

  #데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/shop?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234

  #타임리프 경로 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 80